version: "3"

services:
  app:
    build: ./
    image: docker_best_slim
    # image: docker_best_fat
    ports:
      - 80:3333
    environment:
      - NODE_ENV=production
      - PORT=3333
      - MESSAGE="that IS the slim container"